# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
.gitlab-ci.yml:
  unmanaged: true
.travis.yml:
  unmanaged: true
appveyor.yml:
  unmanaged: true
data/common.yaml:
  unmanaged: true
